AS=pdas --oformat coff
CC=gccwin
LD=pdld

COPTS=-S -O2 -fno-common -ansi -I. -I../pdos/pdpclib -D__WIN32__ -D__NOBIVA__ -D__PDOS__
COBJ=aout.obj hashtab.obj ld.obj lib.obj map.obj report.obj vector.obj write7x.obj

all: clean ld86.exe

ld86.exe: $(COBJ)
  $(LD) -s -nostdlib --no-insert-timestamp -o ld86.exe ../pdos/pdpclib/w32start.obj $(COBJ) ../pdos/pdpclib/msvcrt.lib

.c.obj:
  $(CC) $(COPTS) $<
  $(AS) -o $@ $*.s
  rm -f $*.s

clean:
  rm -f *.obj ld86.exe
